### PR TITLE
WIP: got midi clock sending to external midi devices.

### PR DESCRIPTION
**Pull request by ryanramage**
based on issue #39 , I have changed to 24 ppq using the midi-clock package which gives finer timer resolution. I have added a sendClock on the io,midi.js and added a callback in terminal to tie it all together. I have tested it with external hardware and the clock messages seem to be syncd

I think I may have slowed down the internal orca clock though. I am wondering if the microPosition should be divided by 6 instead of 24. Anyway, I will open this up to others to have a look at.

### CODE REVIEW

**Comment by hamstah** [comment]
looks alright, it should be 6 not 24 yes.
orca frames are 4 per beat so and midi clock is 24, so we need %6 on the midi clock to get orca frames :)

**Comment by ryanramage** [comment]
thanks. for checking it out - I will make that change and clean things up a bit.

**Comment by neauoire** [comment]
I don't want to include more node modules in the project, would it be possible to make this without midi-clock.js? Or maybe move the relevant parts into Orca?

**Comment by ryanramage** [comment]
Yes it would be really easy to move the files into orca. It is a tiny project. I will do that this weekend and clean it up. Thanks for the feedback

**Comment by neauoire** [comment]
Awesome, thanks! Looking forward to merge.

**Comment by neauoire** [comment]
I was wondering how far you got on this? 
I might give this a shot today :)

**Comment by ryanramage** [comment]
It was working, but

 1 - It adds a dependency (evil evil haha) ;)
 2 - the value of the ppq needs to change from 24 to 6 as mentioned above in the comments (unless orca has changed timings)

**Comment by neauoire** [comment]
Gotcha :) 

1 - I'll find the bits we need.
2 - I'll do some work on the clock stuff 👍

**Comment by ryanramage** [comment]
Lucky day, this package (https://github.com/livejs/midi-clock) has no other dependencies and has only 2 files so you can pretty easy copy it

**Comment by neauoire** [comment]
I think I might as well go ahead and add midi-clock.. 
It's small.

**Comment by neauoire** [comment]
Are you around at the moment? 
I'm trying to implement this but I'm having a bit of trouble X(

**Comment by neauoire** [comment]
I'm a bit confused.. I've imported the midi clock module to test and see what it was doing and everything. But none of it seems to matter for the scope sending midi clock out isn't? Besides `device.send([0xF8], 0)`? Couldn't we just add this, to `terminal.io.midi.run()` ?

```
if(terminal.orca.f % 6 === 0){ device.send([0xF8], 0) }
```

**Comment by neauoire** [comment]
Alright :) Midi clock out is working, just added this one line, sending it 6 times each frame.

**Comment by premek** [comment]
> just added this one line, sending it 6 times each frame.

what line?

**Pull request closed without merging**
