### PR TITLE
Add Remora led controller as a companion application

### PR DESCRIPTION
**Pull request by martinberlin**
Please review and add if you like. Send me your address and I will send a full half a meter 72 RGB UDP Led controller to you.

### CODE REVIEW

**Comment by neauoire** [comment]
Orca's new friend :) I wanna see more videos!

**Comment by martinberlin** [comment]
Thanks I will keep the fork since a new midi keyboard will be on the way soon and I want to try a new operator, maybe "_" or "=" that will combine a Midi + UDP call at the same time (Just an Idea I've had while sleeping)
Thanks and keep up the good work! 

If you want to get a half meter Stripe, just send me your address to martin@luckycloud.de and I will send it to you with the firmware installed (And a WiFi manager, so you just need to set the credentials once, and then do a ip:led.local in Orca)

**Comment by neauoire** [comment]
Thanks a lot! I cannot bring any new hardware into the boat right now, but in august I am moving to montreal for a little while and I could totally experiment with that then :)

**Comment by martinberlin** [comment]
Great, tell me then your address when you get there! 
I'm having a lot of fun with Orca :)

**Pull request merged**
