### PR TITLE
Browser version, again

### PR DESCRIPTION
**Pull request by ondras**
...much simpler this time. Just a new HTML document that links to existing resources, and a few browser-specific stubs/mocks.

(I also created a common `style.css` to make CSS sharing easier.)

### CODE REVIEW

**Comment by neauoire** [comment]
That's more like it 👍 

Thank you so much for taking the time! I will do some changes to the controller class so the web version has access to the controls.

**Comment by ondras** [comment]
Great, thanks!

> Thank you so much for taking the time! I will do some changes to the controller class so the web version has access to the controls.

That would be cool. In the meantime, I have started a little experiment to provide a dgram-compatible API for a browser: https://smaug.cz/~ondras/dgram/parent.html

So ideally one would be able to run a page with two iframes: Orca and Pilot. And these two will send each other fake UDP packets :)

**Comment by neauoire** [comment]
Can you run this in chrome?
I get a couple of errors.

Screen Shot 2019-05-10 at 5 19 36 PM

**Comment by ondras** [comment]
>  get a couple of errors.

That is because of the file:// pseudo-protocol. It works (FF, Chrome) when using HTTP (localhost etc).

**Comment by ondras** [comment]
I tried to publish it using GitHub pages and it works!

https://ondras.github.io/Orca/browser/

(Note that I also had to add `.nojekyll` because some of your files start with underscore; https://help.github.com/en/articles/files-that-start-with-an-underscore-are-missing)

**Comment by neauoire** [comment]
Gotcha! I'll try to publish it as well.

**Comment by neauoire** [comment]
I've never used modules like this so I'm a bit confused. I'm getting this:

```
TypeError: Error resolving module specifier: desktop/sources/scripts/terminal.js
```

From [index.html](https://hundredrabbits.github.io/Orca/index.html)

**Comment by ondras** [comment]
Module specifiers (the "path" or "url" component of an `import` statement) must be either absolute URLs, or start with a dot: https://html.spec.whatwg.org/multipage/webappapis.html#resolve-a-module-specifier

**Comment by ondras** [comment]
I think that it would be sufficient to add "./" before your module specifiers in root index.html.

**Pull request merged**
