### PR TITLE
Persistant zoom level

### PR DESCRIPTION
**Pull request by mashaal**
1 - Window state saved to `userData` json file
2 - Zoom preference saved to local storage

### CODE REVIEW

**Comment by neauoire** [comment]
Instead of affecting `main.js`, could you wait until the application has loaded and do this logic in the terminal instead?

**Comment by mashaal** [comment]
Hm... that may introduce some jumpiness?

**Comment by neauoire** [comment]
I'm okay with that

**Comment by neauoire** [comment]
Actually, let's merge the zoom for now. :)

**Comment by neauoire** [comment]
👍

**Comment by mashaal** [comment]
Np, the saved state in `main.js` is a v nice addition, don't count it out! 💫

**Comment by neauoire** [comment]
I won't I just wanna think about it some more :)

**Pull request merged**
