### PR TITLE
Vim keybindings

### PR DESCRIPTION
**Pull request by rumblesan**
Likely needs a bit of polish but should be enough for people to play with and decide if they like it at this point. Doesn't affect the normal operation of Orca and has to be explicitly enabled from the app menu.

To enable Vim Mode, toggle it from the `View` drop down on the app menu. Once enabled it will automatically start in command mode. There's currently no indicator as to what mode you're in, but I'll add that if people feel this work is useful. The vim mode setting is saved in local storage, so should persist between runs as well.

## Keybindings
`h`, `j`, `k`, `l` as left, down, up, right movement keys respectively
`Escape` or `Ctrl/Meta-[` to enter command mode
`Backspace` or `x` as deletion
`u` as undo
`Ctrl/Meta-r` as redo
`y` as copy
`d` as cut
`p` as paste
`P` as paste with overlap
`a` as select all
`Tab` to toggle hardmode
`:` to enter commands - same as Toggling commander from the `View` drop down
`i` to enter normal Orca control mode
`I` to enter normal Orca control mode but with the cursor in insert mode
`r` to allow replacing of a single character
`~` to switch the case of a letter

Standard movements/selection stuff seems to be working fine, but there may be issues using `Meta` with the movement keys (`Meta-h` automatically hides the active app on OSX for example)

There's certainly more stuff that could/should be added. Mode indicators are the most obvious thing missing. I'm also a very new Orca user, so there may be unforseen issues as well.
Please let me know if you have feedback/issues

### CODE REVIEW

**Comment by neauoire** [comment]
Awesome, gimme a day or two to test this properly :)

**Comment by rumblesan** [comment]
No worries, just means I can spend more time digging in to orca. If this does seem viable for merging then there's probably a bit of discussion to have about the best way to do some things, but we can cross that bridge when we come to it

**Comment by rumblesan** [comment]
Added visual mode because I kept finding I was trying to use it haha.

`v` to switch from command mode to visual mode
movements will automatically scale the cursor selection without `Shift` having to be pressed.

`Ctrl-[` and `Escape` will remove the selection and leave visual mode with no other side effects.
`Backspace`, `x`, `d`, `p`, `P`, `i`, `I` and `r` will all perform their functions as well as removing the selection and leaving visual mode.

**Comment by robjac** [comment]
was this implemented? merged?

**Comment by neauoire** [comment]
Since it complexifies things quite a bit I haven't merged it, but instead I just tell anyone who want to use this to clone this fork and pull the latest changes from master, it shouldn't have any conflicts. I've been meaning to make a fork with this PR but I haven't gotten around to it yet.

**Comment by rumblesan** [comment]
I'm planning to keep the branch vaguely up to date provided that `commander.js` doesn't change too dramatically, so if the plan is just to point people towards this PR then that's probably fine

**Comment by robjac** [comment]
> I'm planning to keep the branch vaguely up to date provided that `commander.js` doesn't change too dramatically, so if the plan is just to point people towards this PR then that's probably fine

So when i build this repo -- and run Orca, i'm still not seeing a Vim option in the View menu.

Am I doing something wrong? 😅

**Comment by rumblesan** [comment]
@robjac should just be a case of cloning the repo, checking out the `vim-keybindings` branch,  running `npm run build_osx` (or whichever platform you're on) and then running the Orca program within the folder that gets generated.

**Comment by robjac** [comment]
@rumblesan thanks for the quick reply; i'll be trying that today. cheers!

**Comment by robjac** [comment]
@rumblesan can confirm it works. thanks again.

**Pull request closed without merging**
