### PR TITLE
Quick demo with working MIDI

### PR DESCRIPTION
**Pull request by kylestew**
1) Hosts the existing Orca web content in a webview
2) Catches WebMIDI calls and forwards to CoreMIDI
Simple copy of https://github.com/mizuhiki/WebMIDIAPIShimForiOS

### CODE REVIEW

**Comment by neauoire** [comment]
Hey Kyle, why did you close this?
I was thinking, this should be its own repo, something like orca-ios

**Comment by kylestew** [comment]
Oh sorry! I meant to open and close this PR in my own fork for now. I wasn't ready to bring it back to the community yet. An orca-ios repo with the core repo as a submodule seems smart. I'm hoping to easily track the core JS code so the two can keep in sync without a lot of manual updates.

Would you like to host the `orca-ios` repo or should I get it started?

(by the way, today I'm experimenting with AUV3 compatibility.)

**Comment by kylestew** [comment]
AUV3 doesn't feel like it belongs in this app. Kicking MIDI out to an app like AUM allows everything I was hoping to accomplish.

Trying to figure out a way to grab the electron menu building calls so I can convert those to native UI.

**Comment by neauoire** [comment]
I can create an orca-ios repo yeah :) I've been meaning to rebuild the menu stuff for orca for a while, I find that it's pretty inefficient right now. How does it look like for you to create native UI menus?

**Comment by kylestew** [comment]
It looks a bit tricky but possible to access the menu commands from iOS. I'll need to keep a copy of all the menu with its function calls on the JS side since iOS can't pull functions across the webview boundary. I'll basically be remote controlling the JS copy of the menu structure from iOS. Hackish, but a good start that wouldn't require changes to the Orca main code base.

Setup the ios repo and I'll do a PR with what I have so far.

**Comment by kylestew** [comment]
Confirmed. Figured out a way to remote control the menu system. An iOS port looks like it will end up being much easier than expected. Looking forward to making strange musical sequences on my iPad!

**Comment by neauoire** [comment]
After some thought, we think it's probably better if you own the repository, the reason is that we don't have iOS devices to test with right now, and in the foreseable future. We'll put the link to the ios repo in the README once you get it working :)

**Comment by kylestew** [comment]
Thanks! I'll keep you updated on the progress. I plan on posting in the lines Orca [thread](https://llllllll.co/t/orca-livecoding-tool/17689) for some feedback soon. There are probably a few individuals there that can build and test on devices as well.

**Comment by kylestew** [comment]
https://github.com/kylestew/orca-ios

Excited about this!

**Comment by neauoire** [comment]
Ah yes! The lines forum is the perfect place, my, you're about to make a
lot of people happy with this.

**Pull request closed without merging**
