### PR TITLE
New format for CC

### PR DESCRIPTION
**Pull request by okyeron**
add program change and pitchbend to CC via extra parameter

`!0000`
1st param is type `0=cc` `1=program change` `2=pitchbend`
2nd is channel
3rd is CC number, program # or pitchbend LSB
4th is CC value or pitchbend MSB

we could probably add things like poly aftertouch and channel aftertouch as additional options.

### CODE REVIEW

**Comment by neauoire** [comment]
Very very cool, super simple implementation I love it.

**Comment by neauoire** [comment]
Could we put the first param at the end, so it's not necessary, also not to break past patches

**Comment by okyeron** [comment]
yeah sure - I wasnt sure what was the best approach

**Comment by okyeron** [comment]
rearranged params #155

**Pull request merged**
