### PR TITLE
Each operator has a color

### PR DESCRIPTION
**Pull request by giann**
Screenshot 2019-06-07 at 14 19 09

### CODE REVIEW

**Comment by nlebellier** [comment]
Hi maybe a good idea but how can i test this feature ? Git commands wanted /;-) to try it without breaking master branch on my machine.

**Comment by giann** [comment]
@nlebellier just checkout my fork on the `colored-operators` branch:

```sh
git clone https://github.com/giann/Orca.git Orca-colored
cd Orca-colored
git checkout colored-operations
cd desktop
npm install
npm run
```

**Comment by nlebellier** [comment]
Well no colors...
image

I operate `npm start` instead of ``npm run``

**Comment by neauoire** [comment]
There's only 1 operator in your screenshot @nlebellier.

**Comment by nlebellier** [comment]
well with three operators D and T and R. 
image

**Comment by nlebellier** [comment]
i apply a theme to see same result
image

may i miss something ?

**Comment by giann** [comment]
The current theme is in the local storage so you have to reset it.

**Comment by nlebellier** [comment]
ok so i reset theme and it works 
image

So we have to reset theme to get working ??

**Comment by giann** [comment]
In the first instance of this pr i modified the theme so you had to reset it. But now the colors are derived from your theme. I suggest you pull the branch again.

**Comment by nlebellier** [comment]
Yes ! it works now.
i have to checkout your branch and then git pull.
image

Great work ! It helps

**Comment by giann** [comment]
Still willing to merge this? @neauoire

**Comment by neauoire** [comment]
Yes, don't close it just yet.

**Pull request closed without merging**
