### PR TITLE
Controller input

### PR DESCRIPTION
**Pull request by njanssen**
This PR add a new controller input operator `~` to Orca. For me, this operator gives me the ability to control Orca with sensors (e.g. movement sensor) and controllers (e.g. Launchpad).

- This operator outputs the latest value received by the new command `ctrl` for some key (0-z). 
- You can either use Orca's command-line or UDP input to set controller input values. I've added `resources/command.js` as a simple example for sending UDP commands to Orca (e.g. `node command.js 'ctrl:0;64'`).
- See the README for more information about expected input value of the `ctrl` command (between `0-127`) and how output values can be scaled (e.g. `0~az` scales the input value for `0` to a value between `a-z`).
- I kept this PR simple by reusing the existing command and UDP input implementation, but we could also think of extending Orca with OSC input support enabling external apps to send messages such as. `/bmp 120` and `/ctrl 0 127`. This would probably make this feature more accessible. Maybe in a separate PR?

Additionally, I marked the output port of operator `V` to be output. Just made more sense to me visually in Orca ;-)

Please let me know any comments or suggestions you guys might have!

### CODE REVIEW

**Comment by neauoire** [comment]
This is great! But it is unnecessarily complexifying the orca codebase since it could be best implemented by making a domain specific companion app, and communicating to it via UDP. I use orca with sensors and light setups myself, I usually send to little running processes that convert the UDP messages into something usable. 

I do like the change to the V operator tho, could you make a PR with just that one change for now?

**Comment by njanssen** [comment]
Hi @neauoire, thanks for your feedback! I'll create a separate PR for the `V` operator 👍

Wondering .. I created this PR with the intention to input values into Orca from a companion app. I see how I can use the current implementation to send UDP or OSC output from Orca (e.g. to control lights) but how do you currently handle UDP input for your sensors? Do you send the `inject` or `write` command via UDP to Orca? Or are you using a different approach such as sending the data to Orca as MIDI input?

**Comment by neauoire** [comment]
I have a video or two where I write my average hand position from the leap motion into orca, I'll dig em out :)

**Comment by njanssen** [comment]
Closing this PR since it won't be merged in. For those interested in my take on controller input, check out these branches in my fork:
* https://github.com/njanssen/Orca/tree/controller-input - controller input via UDP, as seen in this PR
* https://github.com/njanssen/Orca/tree/osc-input - a variation of this PR that uses OSC to receive controller input values

**Pull request closed without merging**
